<a href="https://colab.research.google.com/github/Data4i/Learning_LLM_From_Scratch/blob/main/torch_examples_2_continuation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
import time

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [ ]:
# Testing Out time ranges of tensor with GPU and pure numpy

tensor_1 = torch.randint(low = 2, high = 50, size = (4,3), device = device).to(dtype = torch.float)
tensor_2 = torch.randint(low = 2, high = 50, size = (3,4), device = device).to(dtype = torch.float)

tensor_start_time = time.time()
multiplied_tensor = tensor_1 @ tensor_2
tensor_end_time = time.time()

numpy_array_1 = np.random.randint(low = 2, high = 50, size = (4,3))
numpy_array_2 = np.random.randint(low = 2, high = 50, size = (4,3))

numpy_start_time = time.time()
multiplied_numpy_array = np.multiply(numpy_array_1, numpy_array_2)
numpy_end_time = time.time()

print(f'Time taken for the GPU Tensor operation to execute: {tensor_end_time - tensor_start_time}')
print(f'Time taken for the numpy operation run on cpu to execute: {numpy_end_time - numpy_start_time}')

Time taken for the GPU Tensor operation to execute: 0.0002522468566894531
Time taken for the numpy operation run on cpu to execute: 9.179115295410156e-05


In [9]:
probabilities = torch.tensor([0.3, 0.7])
samples = torch.multinomial(probabilities, num_samples = 10, replacement = True)
print(samples)

tensor([0, 0, 1, 1, 1, 0, 1, 1, 1, 1])


In [11]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])), dim = 0)
out

tensor([1, 2, 3, 4, 5])

In [12]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [13]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [22]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [20]:
torch.tril(torch.ones(5,5)) == 0

tensor([[False,  True,  True,  True,  True],
        [False, False,  True,  True,  True],
        [False, False, False,  True,  True],
        [False, False, False, False,  True],
        [False, False, False, False, False]])

In [24]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [25]:
input = torch.zeros(2,3,4)
print(f'input: {input}, input_shape: {input.shape}')
out = input.transpose(0,2)
print(f'Output: {out}, Output_shape: {out.shape}')

input: tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]), input_shape: torch.Size([2, 3, 4])
Output: tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]), Output_shape: torch.Size([4, 3, 2])


In [26]:
# Stacking Tensors
tensor_1 = torch.tensor([1,2,3])
tensor_2 = torch.tensor([4,5,6])
tensor_3 = torch.tensor([7,8,9])

stacked_tensors = torch.stack([tensor_1, tensor_2, tensor_3])
stacked_tensors

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [29]:
from torch import nn
sample = torch.tensor([10, 10, 10], dtype = torch.float)
linear = nn.Linear(3,3, bias = False)
print(linear(sample))

tensor([ 0.6507,  6.1014, 12.7218], grad_fn=<SqueezeBackward4>)


In [31]:
import torch.nn.functional as F

# Create a tensor
tensor_1 = torch.tensor([1., 2., 3.])

softmax_output = F.softmax(tensor_1, dim = 0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])
