In [1]:
import torch

In [2]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([-45,  37,  17,  31, -40, -17])

In [3]:
tensor = torch.tensor([[0.1, 1.2], [2.3, 4.4], [4.4, 5.6]])
tensor

tensor([[0.1000, 1.2000],
        [2.3000, 4.4000],
        [4.4000, 5.6000]])

In [4]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
ones = torch.ones(4,5)
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [6]:
input = torch.empty(2,3)
input

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00,        nan, 3.0666e-41]])

In [7]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [8]:
linspace = torch.linspace(-10, 10, 5)
linspace

tensor([-10.,  -5.,   0.,   5.,  10.])

In [9]:
logspace = torch.logspace(-10, 10, 5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [10]:
eye = torch.eye(10)
eye

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [11]:
a = torch.empty((2,3), dtype = torch.int)
empty_like = torch.empty_like(a)
empty_like

tensor([[114,  99, 104],
        [ 46, 101, 121]], dtype=torch.int32)